# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0010_auto_20180331_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='parent_id',
        ),
    ]
