# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20180331_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '\u8bc4\u8bba'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blog',
        ),
        migrations.AddField(
            model_name='comment',
            name='blog_id',
            field=models.IntegerField(default=0, verbose_name='\u535a\u5ba2_id'),
        ),
    ]
