# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_auto_20180331_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.IntegerField(blank=True, null=True, verbose_name='parend_id'),
        ),
    ]
