# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_blog_isshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='url',
            field=models.CharField(default='', max_length=100, verbose_name='\u7f51\u5740'),
        ),
    ]
